---
name: Sync changes from upstream template

on: # yamllint disable-line rule:truthy
  # Trigger At 00:00 on each 1st day of month
  schedule:
    - cron: '0 0 1 * *'
  # Manual trigger
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Sync changes from upstream template
        uses: AndreasAugustin/actions-template-sync@v0.6.0-draft
        with:
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          source_repo_path: wayofdev/next-starter-tpl
          upstream_branch: master
          pr_labels: 'type: maintenance'
